apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello2
  name: hello2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello2
  template:
    metadata:
      labels:
        app: hello2
    spec:
      containers:
      - image: registry.k8s.io/echoserver:1.4
        name: echoserver
        resources:
          requests:
            example.com/dongle: 3
          limits:
            example.com/dongle: 3
      restartPolicy: Always
