apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello1
  name: hello1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello1
  template:
    metadata:
      labels:
        app: hello1
    spec:
      containers:
      - image: registry.k8s.io/echoserver:1.4
        name: echoserver
        resources:
          requests:
            example.com/dongle: 4
          limits:
            example.com/dongle: 4
      restartPolicy: Always
